/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Data.Msg;
import com.l2fprod.common.springrcp.JTaskPaneCommandGroup;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import model.Main;
import modelManager.Mainmanager;
import modelManager.LangType;
import static modelManager.LangType.LN;
import static modelManager.LangType.LogIN;
import static modelManager.LangType.hmapForm;
import static modelManager.LangType.hmapSys;
import sysConnect.module;
import Data.MainOpenForm;
/**
 *
 * @author Malimar
 */
public class FrmMain extends javax.swing.JFrame {
    Connection c = module.getConnection();
    String sql;
    String frm;
    static boolean maximized=true;
    int xMouse;
    int yMouse;
    
    Main m = new Main();
    Mainmanager mm = new Mainmanager();
    Msg msg = new Msg();
    
    public FrmMain() {
        initComponents();
        frm = this.getClass().getSimpleName();
        cbLao.setSelected(true);
        
        if (cbEng.isSelected()==true){
            LangType.Lang="L2";
        }else{
            LangType.Lang="L1";
        }    
        
        LangType.showLangForm();
        LangType.showLang();        
        
    }
    public void showLang(){
        try {            
            TaskMain.setTitle(hmapSys.get("TaskMain".concat(frm).toUpperCase())[LN]);
            TaskProduct.setTitle(hmapSys.get("TaskProduct".concat(frm).toUpperCase())[LN]);
            
            lblFormName.setText(hmapForm.get(frm.toUpperCase()) [LangType.LN]);
            btnSetting.setText(hmapSys.get("btnSetting".concat(frm).toUpperCase()) [LN]);
            btnLogin.setText(hmapSys.get("btnLogin".concat(frm).toUpperCase())[LN]);
            btnLogout.setText(hmapSys.get("btnLogout".concat(frm).toUpperCase())[LN]);
            lblPhone.setText(hmapSys.get("lblphone".concat(frm).toUpperCase())[LN]);
            lblF.setText(hmapSys.get("lblF".concat(frm).toUpperCase())[LN]);
            lblAdd.setText(hmapSys.get("lblAdd".concat(frm).toUpperCase())[LN]);
            btnWareHouse.setText(hmapSys.get("btnWareHouse".concat(frm).toUpperCase())[LN]);            
            btnPack.setText(hmapSys.get("btnPack".concat(frm).toUpperCase())[LN]);
            btnZone.setText(hmapSys.get("btnZone".concat(frm).toUpperCase())[LN]);
            btnPick.setText(hmapSys.get("btnPick".concat(frm).toUpperCase())[LN]);
            btnProSize.setText(hmapSys.get("btnProSize".concat(frm).toUpperCase())[LN]);
            btnProUnit.setText(hmapSys.get("btnProUnit".concat(frm).toUpperCase())[LN]);
            btnProCategory.setText(hmapSys.get("btnProCategory".concat(frm).toUpperCase())[LN]);
            btnProGroup.setText(hmapSys.get("btnProGroup".concat(frm).toUpperCase())[LN]);
            
            mm.showCompany(m);
            lblAddress.setText(m.getAddress());
            lblCompany.setText(m.getCompany());
            lblMobile.setText(m.getMobile());
            lblFax.setText(m.getFax());
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMax = new javax.swing.JButton();
        btnMini = new javax.swing.JButton();
        lblFormName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        cbLao = new javax.swing.JCheckBox();
        cbEng = new javax.swing.JCheckBox();
        panelLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jTaskPane1 = new com.l2fprod.common.swing.JTaskPane();
        TaskMain = new com.l2fprod.common.swing.JTaskPaneGroup();
        btnWareHouse = new com.xzq.osc.JocHyperlink();
        btnZone = new com.xzq.osc.JocHyperlink();
        btnPack = new com.xzq.osc.JocHyperlink();
        btnPick = new com.xzq.osc.JocHyperlink();
        TaskProduct = new com.l2fprod.common.swing.JTaskPaneGroup();
        btnProSize = new com.xzq.osc.JocHyperlink();
        btnProUnit = new com.xzq.osc.JocHyperlink();
        btnProCategory = new com.xzq.osc.JocHyperlink();
        btnProGroup = new com.xzq.osc.JocHyperlink();
        jTaskPaneGroup3 = new com.l2fprod.common.swing.JTaskPaneGroup();
        jLabel1 = new javax.swing.JLabel();
        panelSetForm = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainForm");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 204), 1, true));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Saysettha MX", 0, 10)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(true);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMax.setBackground(new java.awt.Color(255, 255, 255));
        btnMax.setFont(new java.awt.Font("Saysettha MX", 0, 10)); // NOI18N
        btnMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Maximize.png"))); // NOI18N
        btnMax.setContentAreaFilled(false);
        btnMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMax.setOpaque(true);
        btnMax.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Maximize.png"))); // NOI18N
        btnMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaxMouseExited(evt);
            }
        });
        btnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxActionPerformed(evt);
            }
        });

        btnMini.setBackground(new java.awt.Color(255, 255, 255));
        btnMini.setFont(new java.awt.Font("Saysettha MX", 0, 10)); // NOI18N
        btnMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minimize.png"))); // NOI18N
        btnMini.setContentAreaFilled(false);
        btnMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMini.setOpaque(true);
        btnMini.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minimize.png"))); // NOI18N
        btnMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMiniMouseExited(evt);
            }
        });
        btnMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiniActionPerformed(evt);
            }
        });

        lblFormName.setFont(new java.awt.Font("Saysettha MX", 1, 18)); // NOI18N
        lblFormName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormName.setText("Mobile");
        lblFormName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMini, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMax, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeaderLayout.createSequentialGroup()
                    .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMini)
                    .addComponent(btnMax)
                    .addComponent(btnClose)))
            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeaderLayout.createSequentialGroup()
                    .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel3.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgScreen/chesters logo.png"))); // NOI18N

        lblCompany.setFont(new java.awt.Font("Saysettha MX", 1, 18)); // NOI18N
        lblCompany.setText("Chester");
        lblCompany.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblPhone.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone.setText("Mobile");
        lblPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblF.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblF.setText("Fax");
        lblF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblMobile.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblMobile.setText(" ");
        lblMobile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblFax.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblFax.setText(" ");
        lblFax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAdd.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdd.setText("Address");
        lblAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAddress.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblAddress.setText(" ");
        lblAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setOpaque(true);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setOpaque(true);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSetting.setBackground(new java.awt.Color(255, 255, 255));
        btnSetting.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnSetting.setText("Setting");
        btnSetting.setContentAreaFilled(false);
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.setOpaque(true);
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
        });

        cbLao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbLao);
        cbLao.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        cbLao.setText("ລາວ");
        cbLao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbLao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbLaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbLaoMouseExited(evt);
            }
        });
        cbLao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLaoActionPerformed(evt);
            }
        });

        cbEng.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbEng);
        cbEng.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        cbEng.setText("English");
        cbEng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbEng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbEngMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbEngMouseExited(evt);
            }
        });
        cbEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEngActionPerformed(evt);
            }
        });

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UserLogin.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Password.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUsername.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUsername.setToolTipText("Email");

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpassword.setToolTipText("Password");
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsername))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpassword)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFax, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbEng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbLao)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLao)
                            .addComponent(cbEng))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCompany)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhone)
                                    .addComponent(lblMobile))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblF)
                                    .addComponent(lblFax))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAdd)
                                    .addComponent(lblAddress)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLogout)
                                    .addComponent(btnLogin)
                                    .addComponent(btnSetting))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jTaskPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTaskPane1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N

        TaskMain.setExpanded(false);
        TaskMain.setSpecial(true);
        TaskMain.setTitle("Main Menu                                       ");
        TaskMain.setFont(new java.awt.Font("Saysettha MX", 1, 12)); // NOI18N

        btnWareHouse.setActiveColor(new java.awt.Color(102, 0, 102));
        btnWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Warehouse.png"))); // NOI18N
        btnWareHouse.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnWareHouse.setText("Warehouse");
        btnWareHouse.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnWareHouse.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnWareHouse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnWareHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWareHouseActionPerformed(evt);
            }
        });
        TaskMain.getContentPane().add(btnWareHouse);

        btnZone.setActiveColor(new java.awt.Color(102, 0, 102));
        btnZone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Zone.png"))); // NOI18N
        btnZone.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnZone.setText("Zone");
        btnZone.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnZone.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnZone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoneActionPerformed(evt);
            }
        });
        TaskMain.getContentPane().add(btnZone);

        btnPack.setActiveColor(new java.awt.Color(102, 0, 102));
        btnPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/StPack.png"))); // NOI18N
        btnPack.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnPack.setText("Pack");
        btnPack.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnPack.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnPack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackActionPerformed(evt);
            }
        });
        TaskMain.getContentPane().add(btnPack);

        btnPick.setActiveColor(new java.awt.Color(102, 0, 102));
        btnPick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pick.png"))); // NOI18N
        btnPick.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnPick.setText("Pick");
        btnPick.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnPick.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnPick.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPickActionPerformed(evt);
            }
        });
        TaskMain.getContentPane().add(btnPick);

        jTaskPane1.add(TaskMain);

        TaskProduct.setSpecial(true);
        TaskProduct.setTitle("Product");
        TaskProduct.setFont(new java.awt.Font("Saysettha MX", 1, 12)); // NOI18N

        btnProSize.setActiveColor(new java.awt.Color(102, 0, 102));
        btnProSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ProSize.png"))); // NOI18N
        btnProSize.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnProSize.setText("ProductSize");
        btnProSize.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnProSize.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnProSize.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProSizeActionPerformed(evt);
            }
        });
        TaskProduct.getContentPane().add(btnProSize);

        btnProUnit.setActiveColor(new java.awt.Color(102, 0, 102));
        btnProUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ProductUnit.png"))); // NOI18N
        btnProUnit.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnProUnit.setText("Product Unit");
        btnProUnit.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnProUnit.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnProUnit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProUnitActionPerformed(evt);
            }
        });
        TaskProduct.getContentPane().add(btnProUnit);

        btnProCategory.setActiveColor(new java.awt.Color(102, 0, 102));
        btnProCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ProductCategory.png"))); // NOI18N
        btnProCategory.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnProCategory.setText("ProCategory");
        btnProCategory.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnProCategory.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnProCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProCategoryActionPerformed(evt);
            }
        });
        TaskProduct.getContentPane().add(btnProCategory);

        btnProGroup.setActiveColor(new java.awt.Color(102, 0, 102));
        btnProGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ProductGroup.png"))); // NOI18N
        btnProGroup.setRolloverColor(new java.awt.Color(102, 0, 102));
        btnProGroup.setText("ProGroup");
        btnProGroup.setUnvisitColor(new java.awt.Color(51, 51, 255));
        btnProGroup.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnProGroup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProGroupActionPerformed(evt);
            }
        });
        TaskProduct.getContentPane().add(btnProGroup);

        jTaskPane1.add(TaskProduct);

        jTaskPaneGroup3.setExpanded(false);
        jTaskPaneGroup3.setSpecial(true);
        jTaskPaneGroup3.setTitle("Report");
        jTaskPaneGroup3.setFont(new java.awt.Font("Saysettha MX", 1, 12)); // NOI18N
        jTaskPane1.add(jTaskPaneGroup3);

        jPanel7.add(jTaskPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("                                                                  ");
        jLabel1.setOpaque(true);
        jPanel7.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setViewportView(jPanel7);

        jPanel9.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jScrollPane2.setViewportView(jPanel9);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_START);

        panelSetForm.setLayout(new java.awt.BorderLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        panelSetForm.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(panelSetForm, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel4);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        try {
            System.exit(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
        try {
            if (maximized){
                this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
                this.setMaximizedBounds(env.getMaximumWindowBounds());
                maximized=false;
            }else{
                setExtendedState(JFrame.NORMAL);
                maximized = true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMaxActionPerformed

    private void btnMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniActionPerformed
        try {
            this.setState(Frame.ICONIFIED);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMiniActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        try {
            btnClose.setBackground(new Color(232,17,35));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        try {
            btnClose.setBackground(new Color(255,255,255));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseEntered
        try {
            btnMax.setBackground(new Color(232,17,35));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMaxMouseEntered

    private void btnMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseExited
        try {
            btnMax.setBackground(new Color(255,255,255));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMaxMouseExited

    private void btnMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseEntered
        try {
            btnMini.setBackground(new Color(232,17,35));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMiniMouseEntered

    private void btnMiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiniMouseExited
        try {
            btnMini.setBackground(new Color(255,255,255));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMiniMouseExited

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
        try {
            xMouse = evt.getX();
            yMouse = evt.getY();
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_panelHeaderMousePressed

    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
        try {
            if (maximized){
                int x = evt.getXOnScreen();
                int y = evt.getYOnScreen();
                this.setLocation(x - xMouse, y - yMouse);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            int w = (int)d.getWidth();
            int h = (int)d.getHeight();
            this.setBounds(0,0,w,h);

            showLang();
            jPanel3.setVisible(false);
            jPanel3.setBackground(new Color(255,255,255));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        txtpassword.setText("");
        txtpassword.requestFocus();
        LangType.LogIN=0;
        panelLogin.setVisible(true);
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        //btnLogout.setBackground(new Color(232,17,35));
        btnLogout.setBackground(new Color(180,150,255));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(180,150,255));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        btnSetting.setBackground(new Color(180,150,255));
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        btnSetting.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSettingMouseExited

    private void cbLaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbLaoMouseEntered
        try {
            cbLao.setBackground(new Color(180,150,255));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbLaoMouseEntered

    private void cbLaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbLaoMouseExited
        try {
            cbLao.setBackground(new Color(255,255,255));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbLaoMouseExited

    private void cbEngMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEngMouseEntered
        cbEng.setBackground(new Color(180,150,255));
    }//GEN-LAST:event_cbEngMouseEntered

    private void cbEngMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEngMouseExited
        cbEng.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_cbEngMouseExited

    private void cbEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEngActionPerformed
        try {
            if(cbEng.isSelected()==true){                
                LangType.LN=1;
                LangType.Lang= "L2";
                showLang();
                panelLogin.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbEngActionPerformed

    private void cbLaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLaoActionPerformed
        try {
            if (cbLao.isSelected()==true){                
                LangType.LN=0;
                LangType.Lang= "L1";
                showLang();
                panelLogin.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbLaoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {           
            m.setUser(txtUsername.getText());
            m.setPassworld(txtpassword.getText());
            mm.showLogin(m);
            if (LangType.LogIN==1){
                msg.showMsgSucess();
                jPanel3.setVisible(true);               
                txtpassword.setText("");  
                txtUsername.setEditable(false);
            }else{
                jPanel3.setVisible(false);  
                msg.showMsgUnSucess();                              
            }
            
            if (cbEng.isSelected()==true){
                LangType.Lang="L2";
            }else{
                LangType.Lang="L1";
            }    
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnWareHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWareHouseActionPerformed
        try {
            FrmWareHouse w = new FrmWareHouse();
            w.setVisible(true);
            jDesktopPane1.add(w);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnWareHouseActionPerformed

    private void btnPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackActionPerformed
        try {
            FrmPack p = new FrmPack();
            p.setVisible(true);
            jDesktopPane1.add(p);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPackActionPerformed

    private void btnZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoneActionPerformed
        try {
            FrmZone z = new FrmZone();
            z.setVisible(true);
            jDesktopPane1.add(z);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnZoneActionPerformed

    private void btnPickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickActionPerformed
        try {
            FrmPick pi = new FrmPick();
            pi.setVisible(true);
            jDesktopPane1.add(pi);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPickActionPerformed

    private void btnProSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProSizeActionPerformed
        try {
            FrmProSize f = new FrmProSize();
            MainOpenForm.Open(f, jDesktopPane1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnProSizeActionPerformed

    private void btnProUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProUnitActionPerformed
        try {
            FrmProUnit u = new FrmProUnit();
            u.setVisible(true);
            jDesktopPane1.add(u);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnProUnitActionPerformed

    private void btnProCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProCategoryActionPerformed
        try {
            FrmProCategory fm = new FrmProCategory();
            MainOpenForm.Open(fm, jDesktopPane1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnProCategoryActionPerformed

    private void btnProGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProGroupActionPerformed
        try {
            FrmProGroup fg = new FrmProGroup();
            MainOpenForm.Open(fg, jDesktopPane1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnProGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.l2fprod.common.swing.JTaskPaneGroup TaskMain;
    private com.l2fprod.common.swing.JTaskPaneGroup TaskProduct;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnMini;
    private com.xzq.osc.JocHyperlink btnPack;
    private com.xzq.osc.JocHyperlink btnPick;
    private com.xzq.osc.JocHyperlink btnProCategory;
    private com.xzq.osc.JocHyperlink btnProGroup;
    private com.xzq.osc.JocHyperlink btnProSize;
    private com.xzq.osc.JocHyperlink btnProUnit;
    private javax.swing.JButton btnSetting;
    private com.xzq.osc.JocHyperlink btnWareHouse;
    private com.xzq.osc.JocHyperlink btnZone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbEng;
    private javax.swing.JCheckBox cbLao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.l2fprod.common.swing.JTaskPane jTaskPane1;
    private com.l2fprod.common.swing.JTaskPaneGroup jTaskPaneGroup3;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFormName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelSetForm;
    public static javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
