/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.sql.*;
import Data.ButtonColor;
import modelManager.LangType;
import static modelManager.LangType.LN;
import sysConnect.module;

public class FrmVendor extends javax.swing.JInternalFrame {

    Connection c = module.getConnection();
    String sql, frm;
    
    public FrmVendor() {
        initComponents();
        frm = this.getClass().getSimpleName();
        LangType.showLang();
        LangType.showLangForm();
    }
    public void showLang(){
        try {
            lblFormName.setText(LangType.hmapForm.get(frm.toUpperCase())[LN]);
            btnSave.setText(LangType.hmapSys.get("btnSave".concat(frm).toUpperCase())[LN]);
            btnData.setText(LangType.hmapSys.get("btnData".concat(frm).toUpperCase())[LN]);
            lblVendorNo.setText(LangType.hmapSys.get("lblVendorNo".concat(frm).toUpperCase())[LN]);
            lblVendor_L1.setText(LangType.hmapSys.get("lblVendor_L1".concat(frm).toUpperCase())[LN]);
            lblVendor_L2.setText(LangType.hmapSys.get("lblVendor_L2".concat(frm).toUpperCase())[LN]);
            lblPhone1.setText(LangType.hmapSys.get("lblPhone1".concat(frm).toUpperCase())[LN]);
            lblPhone2.setText(LangType.hmapSys.get("lblPhone2".concat(frm).toUpperCase())[LN]);
            lblFax.setText(LangType.hmapSys.get("lblFax".concat(frm).toUpperCase())[LN]);
            lblEmail.setText(LangType.hmapSys.get("lblEmail".concat(frm).toUpperCase())[LN]);
            lblWebSite.setText(LangType.hmapSys.get("lblWebSite".concat(frm).toUpperCase())[LN]);
            lblPostalCode.setText(LangType.hmapSys.get("lblPostalCode".concat(frm).toUpperCase())[LN]);
            lblBankName.setText(LangType.hmapSys.get("lblBankName".concat(frm).toUpperCase())[LN]);
            lblBankAccount.setText(LangType.hmapSys.get("lblBankAccount".concat(frm).toUpperCase())[LN]);
            lblCreateVendor.setText(LangType.hmapSys.get("lblCreateVendor".concat(frm).toUpperCase())[LN]);
            lblAddress.setText(LangType.hmapSys.get("lblAddress".concat(frm).toUpperCase())[LN]);            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFormName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblVendorNo = new javax.swing.JLabel();
        txtunit_l1 = new javax.swing.JTextField();
        lblVendor_L1 = new javax.swing.JLabel();
        txtUnit_L2 = new javax.swing.JTextField();
        btnData = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblVendor_L2 = new javax.swing.JLabel();
        txtUnitDescriptions = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtUnitDescriptions1 = new javax.swing.JTextField();
        lblPhone2 = new javax.swing.JLabel();
        txtUnitDescriptions2 = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtUnitDescriptions3 = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtUnitDescriptions4 = new javax.swing.JTextField();
        lblWebSite = new javax.swing.JLabel();
        txtUnitDescriptions5 = new javax.swing.JTextField();
        lblPostalCode = new javax.swing.JLabel();
        txtUnitDescriptions6 = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        txtUnitDescriptions8 = new javax.swing.JTextField();
        lblBankAccount = new javax.swing.JLabel();
        txtUnitDescriptions9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblAddress = new javax.swing.JLabel();
        lblCreateVendor = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vendor.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblFormName.setFont(new java.awt.Font("Saysettha MX", 1, 18)); // NOI18N
        lblFormName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormName.setText("Vendor");
        lblFormName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblFormName, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblVendorNo.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblVendorNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVendorNo.setText("Vendor No");
        lblVendorNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtunit_l1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtunit_l1.setToolTipText("");
        txtunit_l1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunit_l1KeyReleased(evt);
            }
        });

        lblVendor_L1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblVendor_L1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVendor_L1.setText("Vendor L1");
        lblVendor_L1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnit_L2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnit_L2.setToolTipText("");

        btnData.setBackground(new java.awt.Color(255, 255, 255));
        btnData.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnData.setText("Data");
        btnData.setContentAreaFilled(false);
        btnData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnData.setOpaque(true);
        btnData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataMouseExited(evt);
            }
        });
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblVendor_L2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblVendor_L2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVendor_L2.setText("Vendor L2");
        lblVendor_L2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions.setToolTipText("");

        lblPhone1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblPhone1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone1.setText("Phone 1");
        lblPhone1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions1.setToolTipText("");

        lblPhone2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblPhone2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone2.setText("Phone 2");
        lblPhone2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions2.setToolTipText("");

        lblFax.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblFax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFax.setText("Fax");
        lblFax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions3.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions3.setToolTipText("");

        lblEmail.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email");
        lblEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions4.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions4.setToolTipText("");

        lblWebSite.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblWebSite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWebSite.setText("WebSite");
        lblWebSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions5.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions5.setToolTipText("");

        lblPostalCode.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblPostalCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPostalCode.setText("Postal Code");
        lblPostalCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions6.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions6.setToolTipText("");

        lblBankName.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblBankName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankName.setText("Bank Name");
        lblBankName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions8.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions8.setToolTipText("");

        lblBankAccount.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblBankAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBankAccount.setText("Bank Account");
        lblBankAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnitDescriptions9.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtUnitDescriptions9.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lblAddress.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress.setText("Address");
        lblAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCreateVendor.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblCreateVendor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCreateVendor.setText("Create Vendor");
        lblCreateVendor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblVendor_L2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPhone1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPhone2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblFax, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblWebSite, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPostalCode, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitDescriptions6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreateVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBankName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUnitDescriptions8, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txtUnitDescriptions9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblVendorNo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(lblVendor_L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtunit_l1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txtUnit_L2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtunit_l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendorNo))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnit_L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendor_L1))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendor_L2))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone1))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone2))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWebSite))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPostalCode))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankName))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitDescriptions9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankAccount))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCreateVendor, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnData)
                    .addComponent(btnSave))
                .addGap(2, 2, 2))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunit_l1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunit_l1KeyReleased

    }//GEN-LAST:event_txtunit_l1KeyReleased

    private void btnDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseEntered
        try {
            ButtonColor.showButtonEnter(btnData);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDataMouseEntered

    private void btnDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseExited
        ButtonColor.showButtonExited(btnData);
    }//GEN-LAST:event_btnDataMouseExited

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
       
    }//GEN-LAST:event_btnDataActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ButtonColor.showButtonEnter(btnSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        ButtonColor.showButtonExited(btnSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            showLang();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblCreateVendor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFormName;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblVendorNo;
    private javax.swing.JLabel lblVendor_L1;
    private javax.swing.JLabel lblVendor_L2;
    private javax.swing.JLabel lblWebSite;
    public static javax.swing.JTextField txtUnitDescriptions;
    public static javax.swing.JTextField txtUnitDescriptions1;
    public static javax.swing.JTextField txtUnitDescriptions2;
    public static javax.swing.JTextField txtUnitDescriptions3;
    public static javax.swing.JTextField txtUnitDescriptions4;
    public static javax.swing.JTextField txtUnitDescriptions5;
    public static javax.swing.JTextField txtUnitDescriptions6;
    public static javax.swing.JTextField txtUnitDescriptions8;
    public static javax.swing.JTextField txtUnitDescriptions9;
    public static javax.swing.JTextField txtUnit_L2;
    public static javax.swing.JTextField txtunit_l1;
    // End of variables declaration//GEN-END:variables
}
