/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import Data.ButtonColor;
import Data.Msg;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import model.Main;
import model.Warehouse;
import modelManager.LangType;
import static modelManager.LangType.LN;
import modelManager.MaxIDTbl;
import sysConnect.module;
import java.util.Date;
import javax.swing.JButton;
import modelManager.WarehouseManager;

public class FrmWareHouse extends javax.swing.JInternalFrame {

    Connection c = module.getConnection();
    String sql, frm;
    DefaultTableModel model = new DefaultTableModel();
    Warehouse wh = new Warehouse();
    WarehouseManager whm = new WarehouseManager();
    public static int Stockid = 0;
    Main m = new Main();
    Msg msg = new Msg();
    
    public FrmWareHouse() {
        initComponents();
        frm = this.getClass().getSimpleName();
        LangType.showLang();
        LangType.showLangForm();                        
    }
    
    public void showLang(){
        try {                        
            lblFormName.setText(LangType.hmapForm.get(frm.toUpperCase())[LN]);          
            btnSave.setText(LangType.hmapSys.get("btnSave".concat(frm).toUpperCase())[LN]);
            btnShowData.setText(LangType.hmapSys.get("btnshowData".concat(frm).toUpperCase())[LN]);
            lblStockNameL1.setText(LangType.hmapSys.get("lblStockNameL1".concat(frm).toUpperCase())[LN]);
            lblStockNameL2.setText(LangType.hmapSys.get("lblStockNameL2".concat(frm).toUpperCase())[LN]);
            lblPhone1.setText(LangType.hmapSys.get("lblPhone1".concat(frm).toUpperCase())[LN]);
            lblPhone2.setText(LangType.hmapSys.get("lblPhone2".concat(frm).toUpperCase())[LN]);
            lblFax.setText(LangType.hmapSys.get("lblFax".concat(frm).toUpperCase())[LN]);
            lblAddress.setText(LangType.hmapSys.get("lblAddress".concat(frm).toUpperCase())[LN]);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void showClear(){
        try {
            txtStockName_L1.setText("");
            txtStockName_L2.setText("");
            txtPhone1.setText("");
            txtPhone2.setText("");
            txtFax.setText("");
            txtAddress.setText("");
            txtStockName_L1.requestFocus();            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFormName = new javax.swing.JLabel();
        lblStockNameL1 = new javax.swing.JLabel();
        txtStockName_L1 = new javax.swing.JTextField();
        lblStockNameL2 = new javax.swing.JLabel();
        txtStockName_L2 = new javax.swing.JTextField();
        txtPhone1 = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        lblPhone2 = new javax.swing.JLabel();
        txtPhone2 = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnShowData = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Warehouse.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblFormName.setFont(new java.awt.Font("Saysettha MX", 1, 18)); // NOI18N
        lblFormName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormName.setText("Warehouse");
        lblFormName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblStockNameL1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblStockNameL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStockNameL1.setText("Stock Name L1");
        lblStockNameL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtStockName_L1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtStockName_L1.setToolTipText("");
        txtStockName_L1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockName_L1KeyReleased(evt);
            }
        });

        lblStockNameL2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblStockNameL2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStockNameL2.setText("Stock Name L2");
        lblStockNameL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtStockName_L2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtStockName_L2.setToolTipText("");

        txtPhone1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtPhone1.setToolTipText("");

        lblPhone1.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblPhone1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone1.setText("Phone 1");
        lblPhone1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblPhone2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblPhone2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone2.setText("Phone 2");
        lblPhone2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtPhone2.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtPhone2.setToolTipText("");

        lblFax.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblFax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFax.setText("Fax");
        lblFax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtFax.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtFax.setToolTipText("");

        lblAddress.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress.setText("Address");
        lblAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btnShowData.setBackground(new java.awt.Color(255, 255, 255));
        btnShowData.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnShowData.setText("Data");
        btnShowData.setContentAreaFilled(false);
        btnShowData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowData.setOpaque(true);
        btnShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShowDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShowDataMouseExited(evt);
            }
        });
        btnShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDataActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Saysettha MX", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblFormName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblStockNameL1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStockName_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblStockNameL2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStockName_L2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFax, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnShowData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblFormName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockName_L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockNameL1))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockName_L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockNameL2))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone1))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone2))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowData)
                    .addComponent(btnSave))
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            showLang();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnShowDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowDataMouseEntered
        try {
            ButtonColor.showButtonEnter(btnShowData);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnShowDataMouseEntered

    private void btnShowDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowDataMouseExited
        ButtonColor.showButtonExited(btnShowData);
    }//GEN-LAST:event_btnShowDataMouseExited

    private void btnShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDataActionPerformed
        try {
            FrmWarehouseData fw = new FrmWarehouseData(null, closable);
            fw.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnShowDataActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ButtonColor.showButtonEnter(btnSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        ButtonColor.showButtonExited(btnSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try {
             SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date dt = new Date();    
            String xx = df.format(dt);
            
            if (txtStockName_L1.getText().equals("")){
                msg.showMsgWarming();
                txtStockName_L1.setBackground(Color.RED);
                txtStockName_L1.requestFocus();
                
            }else{
                wh.setStocknameL1(txtStockName_L1.getText());
                wh.setStocknameL2(txtStockName_L2.getText());
                wh.setMobile1(txtPhone1.getText());
                wh.setMobile2(txtPhone2.getText());
                wh.setFax(txtFax.getText());
                wh.setStockAddress(txtAddress.getText());
                wh.setCreateBy(FrmMain.txtUsername.getText());
                                
                 if (Stockid==0){
                    MaxIDTbl.maxID("StockID", "tbl_Stock");
                    wh.setStockid(MaxIDTbl.getID);  
                    whm.insertTbl_warehouse(wh);
                    showClear();
                 }else{
                     //This is update table
                     wh.setStockid(Stockid);
                     whm.updateTableStock(wh);
                     showClear();
                 }                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtStockName_L1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockName_L1KeyReleased
        txtStockName_L1.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtStockName_L1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFormName;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblStockNameL1;
    private javax.swing.JLabel lblStockNameL2;
    public static javax.swing.JTextArea txtAddress;
    public static javax.swing.JTextField txtFax;
    public static javax.swing.JTextField txtPhone1;
    public static javax.swing.JTextField txtPhone2;
    public static javax.swing.JTextField txtStockName_L1;
    public static javax.swing.JTextField txtStockName_L2;
    // End of variables declaration//GEN-END:variables
}
